class Settings {

	//
  //  http://www.mirekw.com/ca/rullex_life.html
  //  https://www.conwaylife.com/wiki/List_of_Life-like_cellular_automata
  //  https://catagolue.appspot.com/rules
  //
  static rules = {
    conway: "B3/S23",
    // anneal: "B4678/S35678",
    // anonymous: "B25/S4",
    antColony: "B158/S45678",
    // assimilation: "B4567/S345",
    bacteria: "B34/S456",
    // blinkingCity: "B2345/S23456",
    circuitBoard: "B12/S234",
    cityBuilder: "B13/S123468",
    // coagulations: "B235678/S378",
    // coral2: "B345678/S3456",
    // coral: "B45678/S3",
    dayAndNight: "B34678/S3678",
    diamoeba: "B35678/S5678",
    // dotLife: "B3/S023",
    // dryLife: "B37/S23",
    // easyMaze: "B1/S125",
    eightLife: "B3/S238",
    filler: "B3/S1345678",
    filler2: "B3/S12345678",
    // flakes: "B012345678/S3",
    // flock: "B3/S12",
    fredkin: "B1357/S02468",
    // gemsMinor: "B34578/S456",
    gentle: "B36/S2456",
    // geology: "B3578/S24678",
    gnarl: "B1/S1",
    // gnarl2: "B13/S124",
    // gnarl3: "B12/S12",
    highline: "B36/S23",
    // honeyLife: "B38/S238",
    life34: "B34/S34",
    lifeFreeOrDie: "B2/S0",
    // mazectric: "B1234/S3",
    mazeMice: "B37/S12345",
    // morley: "B368/S245",
    move: "B245/S368",
    // nearLife: "B35/S236",
    niemiec: "B36/S245",
    noDeath: "B3/S012345678",
    noDeath2: "B3678/S012345678",
    // noDeath3: "B3678/S12345678",
    // pedastrianLife: "B38/S23",
    photon: "B24/S",
    psuedoLife: "B238/S357",
    rails: "B2/S0123456",
    replicator: "B1357/S1357",
    // replicator2: "B135/S135",
    // seeds2: "B/S2",
    serviettes: "B1/S234",
    snowflake: "B1/S012345678",
    sortOfLife: "B37/S23",
    spaceFiller: "B2/S2345678",
    // spreader: "B35/S345",
    // stains: "B235678/S3678",
    // twoXtwo: "B36/S125",
    walledCities: "B2345/S45678",
    static: "B/S012345678", 
  };

	static presetList = {
		default: 'default',
		diamondHeart: 'diamondHeart',
		icing: 'icing',
		lemonadeAnts: 'lemonadeAnts',
		tileFactory: 'tileFactory',
		petriDish: 'petriDish',
		parkMap: 'parkMap',
		rose: 'rose',
		theMachine: 'theMachine',
		embers: 'embers',
		cityLights: 'cityLights',
		sparkle: 'sparkle',
	}

	static presetHidden = {
		preset: 'default'
	}

	static presets = {
		icing: {
			ruleSet: Settings.rules.filler2,
			dot: false,
			row: false,
			cross: false,
			diagCross: true,
			square: false,
			block: false,
			triangle: false,
			diamond: true,
			corners: false,
			grid: false,
			seCorner: false,
			sCross: false,
			random: false,
			density: 0,
			colors: 'darkSands',
			colorBy: 'generation',
			flipScale: true,
			bgndDark: false,
			discrete: true,
			shades: 0,
			cellSize: 1
		},
		diamondHeart: {
			ruleSet: Settings.rules.spaceFiller,
			dot: false,
			row: false,
			cross: false,
			diagCross: false,
			square: false,
			block: false,
			triangle: false,
			diamond: true,
			corners: false,
			grid: false,
			seCorner: false,
			sCross: false,
			random: false,
			density: 73,
			colors: "mintHoney",
			colorBy: "generation",
			flipScale: false,
			bgndDark: false,
			discrete: false,
			shades: 0,
			cellSize: 2
		},
		lemonadeAnts: {
	    ruleSet: Settings.rules.antColony,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: false,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: true,
	    density: 2,
	    colors: "lemonade",
	    colorBy: "relativeAge",
	    flipScale: false,
	    bgndDark: false,
	    discrete: false,
	    shades: 0,
	    cellSize: 2
		},
		cityLights: {
	    ruleSet: Settings.rules.mazeMice,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: false,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: true,
	    seCorner: false,
	    sCross: false,
	    random: true,
	    density: 48,
	    colors: "fullRainbow",
	    colorBy: "life",
	    flipScale: false,
	    bgndDark: true,
	    discrete: false,
	    shades: 0,
	    cellSize: 2
		},
		tileFactory: {
			ruleSet: Settings.rules.replicator,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: false,
	    square: true,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: false,
	    density: 2,
	    colors: "fullRainbow",
	    colorBy: "alive",
	    flipScale: true,
	    bgndDark: false,
	    discrete: false,
	    shades: 0,
	    cellSize: 3
		},
		petriDish: {
			ruleSet: Settings.rules.bacteria,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: true,
	    square: false,
	    block: true,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: false,
	    density: 0,
	    colors: "mellowGreen",
	    colorBy: "alive",
	    flipScale: true,
	    bgndDark: true,
	    discrete: false,
	    shades: 0,
	    cellSize: 2
		},
		parkMap: {
			ruleSet: Settings.rules.noDeath2,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: true,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: true,
	    density: 60,
	    colors: "fullRainbow",
	    colorBy: "generation",
	    flipScale: false,
	    bgndDark: true,
	    discrete: true,
	    shades: 0,
	    cellSize: 2
		},
		rose: {
			ruleSet: Settings.rules.rails,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: false,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: true,
	    random: false,
	    density: 0,
	    colors: "district2",
	    colorBy: "generation",
	    flipScale: false,
	    bgndDark: true,
	    discrete: false,
	    shades: 0,
	    cellSize: 2
		},
		theMachine: {
	    ruleSet: Settings.rules.circuitBoard,
	    dot: false,
	    row: false,
	    cross: false,
	    diagCross: true,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: false,
	    density: 0,
	    colors: "fluor",
	    colorBy: "alive",
	    flipScale: false,
	    bgndDark: false,
	    discrete: true,
	    shades: 0,
	    cellSize: 2
		},
		embers: {
	    ruleSet: Settings.rules.sortOfLife,
	    dot: false,
	    row: false,
	    cross: true,
	    diagCross: false,
	    square: false,
	    block: false,
	    triangle: true,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: false,
	    density: 0,
	    colors: "westCoast",
	    colorBy: "generation",
	    flipScale: true,
	    bgndDark: true,
	    discrete: false,
	    shades: 0,
	    cellSize: 2
		},
		sparkle: {
	    ruleSet: Settings.rules.replicator,
	    dot: true,
	    row: false,
	    cross: false,
	    diagCross: false,
	    square: false,
	    block: false,
	    triangle: false,
	    diamond: false,
	    corners: false,
	    grid: false,
	    seCorner: false,
	    sCross: false,
	    random: false,
	    density: 0,
	    colors: "winter-night",
	    colorBy: "fade",
	    flipScale: true,
	    bgndDark: false,
	    discrete: true,
	    shades: 0,
	    cellSize: 2
		}
	}

}
